
addons:
  apt:
    packages:
      - npm

install:
  - npm install -g resume-cli
  - npm install -g jsonresume-theme-kwan

script:
  - mkdir public
  - resume export -r resume.json --format html --theme kwan ./public/index

# Deploy to GitHub pages
deploy:
  provider: pages
  skip_cleanup: true
  local_dir: public
  github_token: $GITHUB_TOKEN # Set in travis-ci.org dashboard
  on:
    branch: master
  target_branch: gh-pages
