language: node_js
node_js:
  - node # latest stable
cache:
  directories:
    - node_modules
install:
  - npm prune
  - npm install
script:
  - npm run build
deploy:
  # https://docs.travis-ci.com/user/deployment/pages
  provider: pages
  skip-cleanup: true
  keep-history: true
  github-token: $GITHUB_TOKEN
  local-dir: public
  on:
    branch: master
