name: Build my resume
on:
  push:
    branches:
      - master
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3
      - name: Compile LaTeX document
        uses: xu-cheng/latex-action@v2
        with:
          root_file: resume.tex
      - name: Upload PDF file
        uses: actions/upload-artifact@v3
        with:
          name: resume
          path: resume.pdf
      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: resume.pdf
          overwrite: true
