name: Build
on:
  push:
    branches:
      - master
jobs:
  build_and_release:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Git repository
        uses: actions/checkout@v3

      - uses: cachix/install-nix-action@v18
        with:
          github_access_token: ${{ secrets.GITHUB_TOKEN }}
      - run: nix build

      - name: Upload binaries to release
        uses: svenstaro/upload-release-action@v2
        with:
          file: result/resume.pdf
          overwrite: true
